nav:
  - Home: README.md
  - Tutorials:
      - Overview: tutorial/README.md
      - Hello Nais:
          - Part 1 - Create application: tutorial/hello-nais/hello-nais-1.md
          - Part 2 - Make it NAIS: tutorial/hello-nais/hello-nais-2.md
          - Part 3 - Ship it: tutorial/hello-nais/hello-nais-3.md
          - Part 4 - Clean up: tutorial/hello-nais/hello-nais-4.md

  - How-to guides:
      - Overview: how-to/README.md
      - Leader Election: how-to/leader-election.md
      - naisdevice:
          - Install naisdevice: how-to/naisdevice/install-naisdevice.md
          - Uninstall naisdevice: how-to/naisdevice/uninstall-naisdevice.md
          - Update naisdevice: how-to/naisdevice/update-naisdevice.md
          - Troubleshoot naisdevice: how-to/naisdevice/uninstall-naisdevice.md

      - NAIS team: how-to/create-team.md
      - Command line access: how-to/command-line-access.md
      - CI/CD:
          - Overview: how-to/cicd/README.md
          - Build and deploy using GitHub Actions: how-to/cicd/github-action.md
      - Workload CRUD-operations: how-to/workload-crud-operations.md
      - Observability:
          - Overview: how-to/observability/README.md
          - Metrics:
              - Overview: how-to/observability/metrics/README.md
              - Expose metrics: how-to/observability/metrics/expose.md
              - Push metrics: how-to/observability/metrics/push.md
              - Grafana from infoscreen: how-to/observability/metrics/grafana-from-infoscreen.md
          - Tracing:
              - Overview: how-to/observability/tracing/README.md
              - Enable tracing: how-to/observability/tracing/enable-tracing.md
          - Alerts:
              - Overview: how-to/observability/alerts/README.md
              - Create alerts: how-to/observability/alerts/create.md
              - Customize alerts: how-to/observability/alerts/custom.md
              - Recording rules: how-to/observability/alerts/recording.md
          - Logs:
              - Overview: how-to/observability/logs/README.md
              - Enable logging: how-to/observability/logs/enable.md
              - Secure logs: how-to/observability/logs/secure-logs.md
              - Ship logs with curl: how-to/observability/logs/manual.md
      - Storage:
          - Overview: how-to/storage/README.md
          - Create a bucket: how-to/storage/create.md
          - Delete a bucket: how-to/storage/delete.md

  - References:
      - Overview: reference/README.md
      - Application spec: reference/application-spec.md
      - Application example: reference/application-example.md
      - Naisjob spec: reference/naisjob-spec.md
      - Naisjob example: reference/naisjob-example.md
      - Kafka topic spec: reference/kafka-topic-spec.md
      - Kafka topic example: reference/kafka-topic-example.md
      - Metrics: reference/metrics.md
      - Tracing: reference/tracing.md
      - Backup of bucket: reference/bucket-backup.md

  - Explanations:
      - Overview: explanation/README.md
      - Observability:
          - Overview: explanation/observability/README.md
          - Metrics: explanation/observability/metrics.md
          - Tracing: explanation/observability/tracing.md
          - Alerts: explanation/observability/alerts.md
          - Logs: explanation/observability/logs.md
      - NAIS Teams: explanation/nais-teams.md

        # Various how-to guides - moved here temporarily for ease of navigation
        # - Postgres:
        #     - Create a database: how-to/postgres/create.md
        #     - Restoring a backup: how-to/postgres/backup-restore.md
        # - Kafka:
        #     - Overview: how-to/kafka/README.md
        #     - Create a topic: how-to/kafka/create-topic.md
        #     - Consume from a topic: how-to/kafka/consume-topic.md
        #     - Produce to a topic: how-to/kafka/produce-topic.md
        # - OpenSearch:
        #     - Overview: how-to/opensearch/README.md
        #     - Create a instance: how-to/opensearch/create.md
        #     - Access the instance: how-to/opensearch/access.md
        # - BigQuery:
        #     - Overview: how-to/bigquery/README.md
        #     - Create a dataset: how-to/bigquery/create-dataset.md
        # - Bucket:
        #     - Overview: how-to/bucket/README.md
        #     - Create a bucket: how-to/bucket/create.md
        #     - Access a bucket: how-to/bucket/access.md
        # - Secrets:
        #     - Overview: how-to/secrets/README.md
        #     - Create a secret: how-to/secrets/create.md
        #     - Access a secret: how-to/secrets/access.md

site_name: NAIS
repo_url: https://github.com/nais/doc
site_url: https://doc.nais.io/
edit_uri: edit/main/docs/
theme:
  name: material
  language: "en"
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: custom_theme_overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # light-mode
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # dark-mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
copyright: Made with ❤️ by NAV
extra:
  generator: false
  search:
    language: "en"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nais
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nais_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nav
    - icon: fontawesome/brands/internet-explorer
      link: https://nais.io/blog
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/nais/doc/issues/new">feedback form</a> or contact us on Slack</a>.
extra_javascript:
  - amplitude_javascript/events.js
extra_css:
  - material_theme_stylesheet_overrides/uu.css
  - material_theme_stylesheet_overrides/grid.css
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
