site_name: NAIS
repo_url: https://github.com/nais/doc
site_url: https://doc.nais.io/
edit_uri: edit/main/docs/
theme:
  name: material
  language: "en"
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: custom_theme_overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
copyright: Made with ❤️ by NAV
extra:
  search:
    language: "en"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nais
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nais_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nav
    - icon: fontawesome/brands/internet-explorer
      link: https://nais.io/blog
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/nais/doc/issues/new">feedback form</a> or contact us in <a href="https://nav-it.slack.com/archives/C5KUST8N6">#nais channel</a>.
extra_javascript:
  - amplitude_javascript/events.js
extra_css:
  - material_theme_stylesheet_overrides/uu.css
  - material_theme_stylesheet_overrides/grid.css
plugins:
  - search:
      lang: en
  - git-committers:
      enabled: false # !ENV [CI, false]
      repository: nais/doc
      branch: main
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
  - redirects:
      redirect_maps:
        "security/auth/idporten/sidecar.md": "security/auth/idporten.md"
        "security/auth/azure-ad/access-policy.md": "security/auth/azure-ad/configuration.md#access-policy"
        "security/auth/azure-ad/concepts.md": "security/auth/azure-ad/README.md#concepts"
        "appendix/wonderwall.md": "addons/wonderwall.md"
        "security/apigateway/apigateway.md": "security/apigateway/README.md"
        "addons/unleash-next.md": "addons/unleash.md"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: README.md
  - Tutorials:
      - x: basics/application.md
      - y: basics/teams.md
      - z: basics/access.md
  - How-to:
      - database:
          - x: how-to/database/postgres.md
          - y: how-to/database/mongodb.md
          - z: how-to/database/redis.md
      - x: clusters/README.md
      - y: clusters/gcp.md
      - z: clusters/on-premises.md
  - Reference:
      - x: nais-application/example.md
      - y: nais-application/example.md
      - z: nais-application/access-policy.md
  - Explanation:
      - x: naisjob/README.md
      - y: naisjob/example.md
      - z: naisjob/reference.md
