nav:
  - Home: README.md
  - Tutorials:
      - Overview: tutorial/README.md
      - Hello NAIS Part 1: tutorial/hello-nais/hello-nais-1.md
      - Hello NAIS Part 2: tutorial/hello-nais/hello-nais-2.md
      - Hello NAIS Part 3: tutorial/hello-nais/hello-nais-3.md
  - How-to guides:
      - Overview: how-to/README.md
      - Command line access: how-to/command-line-access.md
      - CI/CD:
          - Overview: how-to/cicd/README.md
          - Build and deploy using GitHub Actions: how-to/cicd/github-action.md
      - Workload CRUD-operations: how-to/workload-crud-operations.md
      # - Metrics:
      #     - Overview: how-to/metrics/README.md
      #     - Expose metrics: how-to/metrics/expose.md
      #     - Query metrics: how-to/metrics/query.md
      # - Alerts:
      #     - Overview: how-to/alerts/README.md
      #     - Create an alert: how-to/alerts/create.md
      # - Logging:
      #     - Overview: how-to/logging/README.md
      #     - Access logs: how-to/logging/access.md
      #     - Application logs: how-to/logging/application.md
      # - Postgres:
      #     - Create a database: how-to/postgres/create.md
      #     - Restoring a backup: how-to/postgres/backup-restore.md
      # - Kafka:
      #     - Overview: how-to/kafka/README.md
      #     - Create a topic: how-to/kafka/create-topic.md
      #     - Consume from a topic: how-to/kafka/consume-topic.md
      #     - Produce to a topic: how-to/kafka/produce-topic.md
      # - OpenSearch:
      #     - Overview: how-to/opensearch/README.md
      #     - Create a instance: how-to/opensearch/create.md
      #     - Access the instance: how-to/opensearch/access.md
      # - BigQuery:
      #     - Overview: how-to/bigquery/README.md
      #     - Create a dataset: how-to/bigquery/create-dataset.md
      # - Bucket:
      #     - Overview: how-to/bucket/README.md
      #     - Create a bucket: how-to/bucket/create.md
      #     - Access a bucket: how-to/bucket/access.md
      # - Secrets:
      #     - Overview: how-to/secrets/README.md
      #     - Create a secret: how-to/secrets/create.md
      #     - Access a secret: how-to/secrets/access.md

  - References:
      - Overview: reference/README.md
      - Application spec: reference/application-spec.md
      - Application example: reference/application-example.md
      - Naisjob spec: reference/naisjob-spec.md
      - Naisjob example: reference/naisjob-example.md
      - Kafka topic spec: reference/kafka-topic-spec.md
      - Kafka topic example: reference/kafka-topic-example.md

  - Explanations:
      - Overview: explanation/README.md
site_name: NAIS
repo_url: https://github.com/nais/doc
site_url: https://doc.nais.io/
edit_uri: edit/main/docs/
theme:
  name: material
  language: "en"
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: custom_theme_overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # light-mode
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # dark-mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
copyright: Made with ❤️ by NAV
extra:
  generator: false
  search:
    language: "en"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nais
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nais_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nav
    - icon: fontawesome/brands/internet-explorer
      link: https://nais.io/blog
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/nais/doc/issues/new">feedback form</a> or contact us on Slack</a>.
extra_javascript:
  - amplitude_javascript/events.js
extra_css:
  - material_theme_stylesheet_overrides/uu.css
  - material_theme_stylesheet_overrides/grid.css
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
